import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  async function deleteThemeCookie(formData) {
    'use server';
    cookies().delete('chat-app');
  }

  const token = cookies().get('chat-app')?.value;

  return (
    <html lang="en">
      <body className={inter.className}>
        {token && <nav className="nav">
          <Link href='/'>Home</Link>
          <form action={deleteThemeCookie}>
            <button type="submit">Se déconnecter</button>
          </form>
        </nav>}
        {children}
      </body>

    </html>
  );
}
